"""initial schema

Revision ID: 5aef4e516027
Revises: 
Create Date: 2026-06-29 19:19:08.662856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aef4e516027'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_id'), 'package', ['id'], unique=False)
    op.create_foreign_key(None, 'booking', 'package', ['package_id'], ['id'])
    op.add_column('destination', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('destination', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'otp')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'name')
    op.drop_column('destination', 'updated_at')
    op.drop_column('destination', 'created_at')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_index(op.f('ix_package_id'), table_name='package')
    op.drop_table('package')
    # ### end Alembic commands ###
